#services:
#    acme_user.registration.form.type:
#        class: Ziki\UserBundle\Form\Type\RegistrationFormType
#        arguments: [%fos_user.model.user.class%]
#        tags:
#            - { name: form.type, alias: acme_user_registration }