<?php

namespace Ziki\MusicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArtistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends EntityRepository
{
    public function findLatest()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT a FROM ZikiMusicBundle:Artist a ORDER BY a.id ASC ')
        ->setMaxResults(6)
            ->getResult();
    }
}
